name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'liberica'
          cache: maven

      - name: Write release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set release version
        run: ./mvnw --no-transfer-progress --batch-mode versions:set -DnewVersion=${VERSION}

      - name: Build & Deploy Artifacts
        # recursively
        run: ./mvnw --no-transfer-progress --batch-mode -Prelease deploy

      - name: Release to Maven Central
        env:
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_TOKEN: ${{ secrets.JRELEASER_MAVENCENTRAL_TOKEN }}
        run: ./mvnw --no-transfer-progress --batch-mode --non-recursive -Prelease jreleaser:deploy

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.github_token }}
          message: Perform release v${{ env.VERSION }}
        
        # Keep jars only for GitHub Release
      - name: Package plain jars for GitHub Release
        run: ./mvnw clean package -DskipTests

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ env.VERSION }}
          generate_release_notes: true
          files: "**/target/*.jar"
          draft: false

      - name: Set next version
        run: ./mvnw --no-transfer-progress --batch-mode build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT versions:commit

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.github_token }}
          message: Prepare for next release
